import admission_analytic_report
import general_report
import registration_statistics_report
import admission_statistical_report
import admission_statistical_detailed_report
import collage_share_report
